//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsVPN.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToolsVPN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string CascadeConnectionCreate {
            get {
                return ResourceManager.GetString("CascadeConnectionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CascadeConnectionName {
            get {
                return ResourceManager.GetString("CascadeConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\\Program Files\\VPN_Tools.
        /// </summary>
        internal static string ExecDir {
            get {
                return ResourceManager.GetString("ExecDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5555.
        /// </summary>
        internal static string LocalHostPort {
            get {
                return ResourceManager.GetString("LocalHostPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRIDGE.
        /// </summary>
        internal static string LocalHubName {
            get {
                return ResourceManager.GetString("LocalHubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost.
        /// </summary>
        internal static string LocalServer {
            get {
                return ResourceManager.GetString("LocalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pirkon12.
        /// </summary>
        internal static string LocalServerPassword {
            get {
                return ResourceManager.GetString("LocalServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5555.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tools-assistant.softether.net.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\\temp.
        /// </summary>
        internal static string tmp_dir {
            get {
                return ResourceManager.GetString("tmp_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMT.
        /// </summary>
        internal static string vpn_hub {
            get {
                return ResourceManager.GetString("vpn_hub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\\Program Files\\VPN_Tools\\vpnbridge.exe.
        /// </summary>
        internal static string vpnbridge_exe {
            get {
                return ResourceManager.GetString("vpnbridge_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\\Program Files\\VPN_Tools\\vpncmd.exe.
        /// </summary>
        internal static string vpncmd_exe {
            get {
                return ResourceManager.GetString("vpncmd_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMT.
        /// </summary>
        internal static string vpnhubname {
            get {
                return ResourceManager.GetString("vpnhubname", resourceCulture);
            }
        }
    }
}
